//go:build linux && !android

// Package vpn pkg/vpn/skydns_linux_test.go c4-app-vpn
package vpn

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestSkyDNSResolvConfBlock(t *testing.T) {
	orig := "# Generated by NetworkManager\nsearch lan\nnameserver 192.168.1.1\nnameserver 1.0.0.1\n"
	with := withSkyDNSBlock(orig)
	require.Equal(t, "# skydns begin\nnameserver 198.19.0.53\noptions timeout:1\n# skydns end\n"+orig, with)
	require.Equal(t, orig, stripSkyDNSBlock(with))
	require.Equal(t, orig, stripSkyDNSBlock(withSkyDNSBlock(stripSkyDNSBlock(with))), "a block left by a crash is replaced, not stacked")
	require.Equal(t, "192.168.1.1", firstNameserver(stripSkyDNSBlock(with)))
	require.Equal(t, "", firstNameserver("search lan\n"))
	require.Equal(t, "::1", firstNameserver("nameserver bogus\nnameserver ::1\n"))
}
