//go:build windows
// +build windows

// Package skyenv defines variables and constants
package skyenv

const (
	//OS detection at runtime
	OS = "win"
	// SkywirePath is the path to the installation folder for the .msi
	SkywirePath = "C:/Program Files/Skywire"
	// ConfigJSON is the config name generated by the batch file included with the windows .msi
	ConfigJSON = "skywire-config.json"
)

// PackageConfig contains installation paths (for windows)
func PackageConfig() PkgConfig {
	pkgConfig := PkgConfig{
		LauncherBinPath: "C:/Program Files/Skywire",
		LocalPath:       "C:/Program Files/Skywire/local",
		Hypervisor: Hypervisor{
			DbPath:     "C:/Program Files/Skywire/users.db",
			EnableAuth: true,
		},
	}
	return pkgConfig
}
