//go:build linux
// +build linux

// Package skyenv defines variables and constants
package skyenv

const (
	//OS detection at runtime
	OS = "linux"
	// SkywirePath is the path to the installation folder for the linux packages.
	SkywirePath = "/opt/skywire"
	// ConfigJSON is the config name generated by the skywire-autocofig script in the linux packages
	ConfigJSON = "skywire.json"
	// SkyenvFilePath is the path to the SkyenvFile
	SkyenvFilePath = "/etc/profile.d"
	// SkyenvFile contains environmental variables which are detected by `skywire-autoconfig` / `skywire-cli config auto` to set default or persistent values
	SkyenvFile = "skyenv.sh"
)

// PackageConfig contains installation paths (for linux)
func PackageConfig() PkgConfig {
	pkgConfig := PkgConfig{
		LauncherBinPath: "/opt/skywire/apps",
		LocalPath:       "/opt/skywire/local",
		Hypervisor: Hypervisor{
			DbPath:     "/opt/skywire/users.db",
			EnableAuth: true,
		},
	}
	return pkgConfig
}
