//go:build js

// Package skyenv pkg/skyenv/skyenv_js.go c0-com-env
//
// js/wasm build of pkg/skyenv. Paths mirror the LINUX layout: the browser
// build runs against a virtual Linux-like filesystem (the page installs an
// in-memory globalThis.fs seeded with an FHS skeleton — see
// github.com/0magnet/bottle jsfs.js + browseui/seed-skywire.js), with skywire "installed" under /opt/skywire
// exactly as the packages install it. That makes `cli config gen -rp`, the
// package-path readers, and everything else path-shaped behave the way the
// docs describe, inside the browser. Environments that provide no filesystem
// (or the historical empty-path behavior) simply see the calls fail with the
// shim's errors, which every caller already handles.
package skyenv

const (
	// OS names the runtime platform the way the per-OS skyenv files do.
	OS = "js"
	// SkywirePath is the install root inside the virtual filesystem,
	// matching the linux packages.
	SkywirePath = "/opt/skywire"
	// ConfigJSON is the config name generated by the autoconfig script in
	// the linux packages.
	ConfigJSON = "skywire.json"
)

// PackageConfig contains installation paths (mirroring linux) inside the
// virtual filesystem.
func PackageConfig() PkgConfig {
	pkgConfig := PkgConfig{
		LauncherBinPath: "/opt/skywire/bin",
		LocalPath:       "/opt/skywire/local",
		Hypervisor: Hypervisor{
			DbPath: "/opt/skywire/users.db",
			// No password gate in the tab: the UI is reachable only through
			// the page's own vnet (same-origin service worker included), so
			// auth guards nothing — and users.db is deliberately excluded
			// from filesystem snapshots (bbolt stores restore corrupt), so a
			// password would evaporate on every reload anyway.
			EnableAuth: false,
		},
	}
	return pkgConfig
}
