version: "2"

run:
  concurrency: 4
  modules-download-mode: vendor
  issues-exit-code: 1
  tests: true
  timeout: 5m
  skip-files:
    - ".*_cgo\\.go$"

output:
  format: colored-line-number

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: false
    check-blank: true

  goconst:
    min-len: 3
    min-occurrences: 3

  gocyclo:
    min-complexity: 10

  lll:
    line-length: 120
    tab-width: 1

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    check-exported: false

  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude:
    - path: cipher_cgo\.go
      linters:
        - typecheck

    - path: third_party$
    - path: builtin$
    - path: examples$

    - path: src/cipher/bip39/wordlists/.*  
      linters: [misspell]

    - text: "QF1003:"
      linters: [staticcheck]

    - text: "ST1005:"
      linters: [staticcheck]

    - text: "QF1008:"
      linters: [staticcheck]

    - text: "QF1001:"
      linters: [staticcheck]

    - text: "QF1002:"
      linters: [staticcheck]

    - text: "QF1010:"
      linters: [staticcheck]

    - text: "QF1004:"
      linters: [staticcheck]

    - text: "QF1006:"
      linters: [staticcheck]

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
