# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: skycoin
    name: skywire

  draft: true

before:
  hooks:
    - go mod tidy
builds:
  - id: skywire-visor
    binary: skywire-visor
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-visor/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}

  - id: skywire-cli
    binary: skywire-cli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/skywire-cli/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
  - id: skychat
    binary: apps/skychat
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skychat/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
  - id: skysocks
    binary: apps/skysocks
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skysocks/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
  - id: skysocks-client
    binary: apps/skysocks-client
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/skysocks-client/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
  - id: vpn-server
    binary: apps/vpn-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/vpn-server/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
  - id: vpn-client
    binary: apps/vpn-client
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: ./cmd/apps/vpn-client/
    ldflags: -s -w -X github.com/skycoin/dmsg/buildinfo.version={{.Version}} -X github.com/skycoin/dmsg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/dmsg/buildinfo.date={{.Date}}
archives:
  - format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
