# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  # Note: it can only be one: either github or gitlab or gitea
  github:
    owner: skycoin
    name: skywire

  #prerelease: true

before:
  hooks:
    - go mod tidy
    - sed -i '/go conn.handleCall(msg)/c\conn.handleCall(msg)' ./vendor/github.com/godbus/dbus/v5/conn.go
builds:

  - id: skywire-amd64
    binary: skywire
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
    main: ./cmd/skywire/
    ldflags: -s -w -linkmode external -extldflags '-static' -buildid= -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-arm64
    binary: skywire
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc
    main: ./cmd/skywire/
    ldflags: -s -w -linkmode external -extldflags '-static' -buildid= -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-arm
    binary: skywire
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/arm-linux-musleabi-cross/bin/arm-linux-musleabi-gcc
    main: ./cmd/skywire/
    ldflags: -s -w -linkmode external -extldflags '-static' -buildid= -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-armhf
    binary: skywire
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/arm-linux-musleabihf-cross/bin/arm-linux-musleabihf-gcc
    main: ./cmd/skywire/
    ldflags: -s -w -linkmode external -extldflags '-static' -buildid= -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

  - id: skywire-riscv64
    binary: skywire
    goos:
      - linux
    goarch:
      - riscv64
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/riscv64-linux-musl-cross/bin/riscv64-linux-musl-gcc
    main: ./cmd/skywire/
    ldflags: -s -w -linkmode external -extldflags '-static' -buildid= -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}

archives:
  - id: amd64
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
      - services-config.json
    builds:
      - skywire-amd64

  - id: arm64
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
      - services-config.json
    builds:
      - skywire-arm64

  - id: arm
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
      - services-config.json
    builds:
      - skywire-arm

  - id: armhf
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}hf'
    files:
      - dmsghttp-config.json
      - services-config.json
    builds:
      - skywire-armhf

  - id: riscv64
    format: tar.gz
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
      - services-config.json
    builds:
      - skywire-riscv64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
