# GoReleaser configuration for Darwin builds
# Documentation at http://goreleaser.com

version: 2

release:
  github:
    owner: skycoin
    name: skywire

before:
  hooks:
    - go mod tidy
builds:
  - id: skywire
    binary: skywire
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    main: ./cmd/skywire/
    ldflags: -s -w -X github.com/skycoin/skywire/pkg/skywire-utilities/pkg/buildinfo.version=v{{.Version}} -X github.com/skycoin/skywire/pkg/skywire-utilities/pkg/buildinfo.commit={{.ShortCommit}} -X github.com/skycoin/skywire/pkg/skywire-utilities/pkg/buildinfo.date={{.Date}} -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}

archives:
  - id: archive
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire
    allow_different_binary_count: true
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
