# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
release:
  github: ${{ .Env.GITHUB_REPOSITORY_OWNER }}
    name: skywire

before:
  hooks:
    - go mod tidy
    - sed -i '/go conn.handleCall(msg)/c\conn.handleCall(msg)' ./vendor/github.com/godbus/dbus/v5/conn.go

builds:
{{- range .Builds }}
  - id: {{ .ID }}
    binary: {{ .Binary }}
    goos:
      - linux
    goarch:
{{- range .GoArch }}
      - {{ . }}
{{- end }}
{{- if .GoArm }}
    goarm:
{{- range .GoArm }}
      - {{ . }}
{{- end }}
{{- end }}
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/skywire/skywire/musl-data/{{ .CCPath }}
    main: {{ .Main }}
    ldflags: >
      -s -w -linkmode external -extldflags '-static' -buildid=
      -X github.com/skycoin/skywire-utilities/pkg/buildinfo.version=v{{ .Version }}
      -X github.com/skycoin/skywire-utilities/pkg/buildinfo.commit={{ .ShortCommit }}
      -X github.com/skycoin/skywire-utilities/pkg/buildinfo.date={{ .Date }}
      -X github.com/skycoin/skywire/pkg/visor.BuildTag={{.Os}}_{{.Arch}}
{{- end }}

archives:
{{- range .Archives }}
  - id: {{ .ID }}
    format: {{ .Format }}
    wrap_in_directory: false
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - dmsghttp-config.json
    builds:
{{- range .Builds }}
      - {{ . }}
{{- end }}
{{- end }}
{{- end }}
