# GoReleaser configuration for Linux builds
# Builds skywire binary from repo root (no hardware wallet)

version: 2

release:
  github:
    owner: skycoin
    name: skywire

before:
  hooks:
    - go mod tidy
    - go mod vendor
    - sed -i '/go conn.handleCall(msg)/c\conn.handleCall(msg)' ./vendor/github.com/godbus/dbus/v5/conn.go

builds:
  - id: skywire-amd64
    binary: skywire
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

  - id: skywire-386
    binary: skywire
    goos:
      - linux
    goarch:
      - 386
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

  - id: skywire-arm64
    binary: skywire
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

  - id: skywire-arm
    binary: skywire
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

  - id: skywire-armhf
    binary: skywire
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

  - id: skywire-riscv64
    binary: skywire
    goos:
      - linux
    goarch:
      - riscv64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -buildid=

archives:
  - id: amd64
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire-amd64
    files:
      - none*

  - id: arm64
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire-arm64
    files:
      - none*

  - id: arm
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire-arm
    files:
      - none*

  - id: armhf
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}hf'
    ids:
      - skywire-armhf
    files:
      - none*

  - id: 386
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire-386
    files:
      - none*

  - id: riscv64
    formats:
      - tar.gz
    name_template: 'skywire-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    ids:
      - skywire-riscv64
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
