@testable import WalletCore
import XCTest

/// Port of SkycoinCreateFixtureTest.kt. Byte-for-byte replay of
/// transaction.Create fixtures generated by the Go reference implementation:
/// same inputs chosen in the same order, same hour distribution, same
/// serialization, same inner hash.
final class SkycoinCreateFixtureTests: XCTestCase {

    struct UxFixture: Decodable {
        let hash: String
        let time: UInt64
        let bkSeq: UInt64
        let srcTx: String
        let address: String
        let coins: UInt64
        let hours: UInt64
        let calculatedHours: UInt64
    }

    struct DestFixture: Decodable {
        let address: String
        let coins: UInt64
    }

    struct OutFixture: Decodable {
        let address: String
        let coins: UInt64
        let hours: UInt64
    }

    struct CaseFixture: Decodable {
        let name: String
        let uxouts: [UxFixture]
        let to: [DestFixture]
        let changeAddress: String
        let burnFactor: UInt32
        let expectedInputs: [String]
        let expectedOutputs: [OutFixture]
        let expectedInnerHash: String
        let expectedUnsignedHex: String
        let expectedLength: UInt32
    }

    struct WalletFixture: Decodable {
        let seed: String
        let addresses: [String]
        let secrets: [String]
        let publics: [String]
    }

    struct Fixtures: Decodable {
        let wallet: WalletFixture
        let cases: [CaseFixture]
    }

    static func fixtures() throws -> Fixtures { try Fixture.decode(Fixtures.self, "skycoin-fixtures.json") }

    static func unspents(_ c: CaseFixture) -> [SkycoinCreate.UxBalance] {
        c.uxouts.map {
            SkycoinCreate.UxBalance(
                hash: [UInt8](hex: $0.hash)!,
                hashHex: $0.hash,
                bkSeq: $0.bkSeq,
                address: $0.address,
                coins: $0.coins,
                initialHours: $0.hours,
                hours: $0.calculatedHours
            )
        }
    }

    func testWalletChainMatches() throws {
        let fx = try Self.fixtures()
        let keys = try SkycoinCrypto.generateKeyPairs(seed: Array(fx.wallet.seed.utf8), count: fx.wallet.addresses.count)
        for (i, kp) in keys.enumerated() {
            XCTAssertEqual(fx.wallet.secrets[i], kp.secret.hex)
            XCTAssertEqual(fx.wallet.addresses[i], SkycoinCrypto.addressFromPubKey(kp.public))
        }
    }

    func testCreateMatchesReference() throws {
        let fx = try Self.fixtures()
        XCTAssertEqual(fx.cases.count, 5)
        for c in fx.cases {
            let created = try SkycoinCreate.create(
                unspents: Self.unspents(c),
                to: c.to.map { SkycoinCreate.Destination(address: $0.address, coins: $0.coins) },
                changeAddress: c.changeAddress,
                burnFactor: c.burnFactor
            )

            XCTAssertEqual(c.expectedInputs, created.txn.inputs.map(\.hex), "\(c.name): inputs")
            XCTAssertEqual(c.expectedOutputs.count, created.txn.outputs.count, "\(c.name): output count")
            for (i, o) in c.expectedOutputs.enumerated() where i < created.txn.outputs.count {
                let got = created.txn.outputs[i]
                XCTAssertEqual(o.coins, got.coins, "\(c.name): output \(i) coins")
                XCTAssertEqual(o.hours, got.hours, "\(c.name): output \(i) hours")
                XCTAssertEqual(SkycoinCrypto.decodeAddress(o.address)?.hex, got.addressKey.hex, "\(c.name): output \(i) address")
            }
            XCTAssertEqual(c.expectedInnerHash, created.txn.hashInner().hex, "\(c.name): inner hash")
            XCTAssertEqual(c.expectedUnsignedHex, created.txn.serializeHex(), "\(c.name): serialization")
            XCTAssertEqual(c.expectedLength, created.txn.length, "\(c.name): length")
        }
    }

    func testSignedTransactionVerifies() throws {
        let fx = try Self.fixtures()
        let c = fx.cases[0]
        let created = try SkycoinCreate.create(
            unspents: Self.unspents(c),
            to: c.to.map { SkycoinCreate.Destination(address: $0.address, coins: $0.coins) },
            changeAddress: c.changeAddress,
            burnFactor: c.burnFactor
        )

        let keys = try SkycoinCrypto.generateKeyPairs(seed: Array(fx.wallet.seed.utf8), count: fx.wallet.addresses.count)
        var byAddress = [String: SkycoinCrypto.KeyPair]()
        for (i, a) in fx.wallet.addresses.enumerated() { byAddress[a] = keys[i] }
        let inputKeys = try created.txn.inputs.map { uxid in
            let addr = try XCTUnwrap(created.spends.first { $0.hash == uxid }).address
            return try XCTUnwrap(byAddress[addr]).secret
        }

        var txn = created.txn
        try txn.signInputs(keys: inputKeys)

        // Each signature must recover to the address that owns the spent output.
        for (i, uxid) in txn.inputs.enumerated() {
            let hash = Hashes.sha256(txn.hashInner(), uxid)
            let recovered = try XCTUnwrap(Secp256k1.recoverCompact(hash: hash, sig: txn.sigs[i]))
            let addr = try XCTUnwrap(created.spends.first { $0.hash == uxid }).address
            XCTAssertEqual(addr, SkycoinCrypto.addressFromPubKey(recovered), "sig \(i) recovers to owner")
        }

        // Signing must not disturb the priced structure.
        XCTAssertEqual(c.expectedInnerHash, txn.hashInner().hex)
        XCTAssertEqual(txn.serializeHex().count, c.expectedUnsignedHex.count)
    }
}
