// Code generated by mockery v2.52.3. DO NOT EDIT.

package rfclient

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	routing "github.com/skycoin/skywire/pkg/routing"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// FindRoutes provides a mock function with given fields: ctx, rts, opts
func (_m *MockClient) FindRoutes(ctx context.Context, rts []routing.PathEdges, opts *RouteOptions) (map[routing.PathEdges][][]routing.Hop, error) {
	ret := _m.Called(ctx, rts, opts)

	if len(ret) == 0 {
		panic("no return value specified for FindRoutes")
	}

	var r0 map[routing.PathEdges][][]routing.Hop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []routing.PathEdges, *RouteOptions) (map[routing.PathEdges][][]routing.Hop, error)); ok {
		return rf(ctx, rts, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []routing.PathEdges, *RouteOptions) map[routing.PathEdges][][]routing.Hop); ok {
		r0 = rf(ctx, rts, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[routing.PathEdges][][]routing.Hop)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []routing.PathEdges, *RouteOptions) error); ok {
		r1 = rf(ctx, rts, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
