// Code generated by mockery v2.52.3. DO NOT EDIT.

package addrresolver

import (
	context "context"

	cipher "github.com/skycoin/skywire/pkg/skywire-utilities/pkg/cipher"

	mock "github.com/stretchr/testify/mock"

	pfilter "github.com/AudriusButkevicius/pfilter"
)

// MockAPIClient is an autogenerated mock type for the APIClient type
type MockAPIClient struct {
	mock.Mock
}

// Addresses provides a mock function with given fields: ctx
func (_m *MockAPIClient) Addresses(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Addresses")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BindSTCPR provides a mock function with given fields: ctx, port
func (_m *MockAPIClient) BindSTCPR(ctx context.Context, port string) error {
	ret := _m.Called(ctx, port)

	if len(ret) == 0 {
		panic("no return value specified for BindSTCPR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BindSUDPH provides a mock function with given fields: filter, handshake
func (_m *MockAPIClient) BindSUDPH(filter *pfilter.PacketFilter, handshake Handshake) (<-chan RemoteVisor, error) {
	ret := _m.Called(filter, handshake)

	if len(ret) == 0 {
		panic("no return value specified for BindSUDPH")
	}

	var r0 <-chan RemoteVisor
	var r1 error
	if rf, ok := ret.Get(0).(func(*pfilter.PacketFilter, Handshake) (<-chan RemoteVisor, error)); ok {
		return rf(filter, handshake)
	}
	if rf, ok := ret.Get(0).(func(*pfilter.PacketFilter, Handshake) <-chan RemoteVisor); ok {
		r0 = rf(filter, handshake)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan RemoteVisor)
		}
	}

	if rf, ok := ret.Get(1).(func(*pfilter.PacketFilter, Handshake) error); ok {
		r1 = rf(filter, handshake)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with no fields
func (_m *MockAPIClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Resolve provides a mock function with given fields: ctx, netType, pk
func (_m *MockAPIClient) Resolve(ctx context.Context, netType string, pk cipher.PubKey) (VisorData, error) {
	ret := _m.Called(ctx, netType, pk)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 VisorData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, cipher.PubKey) (VisorData, error)); ok {
		return rf(ctx, netType, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, cipher.PubKey) VisorData); ok {
		r0 = rf(ctx, netType, pk)
	} else {
		r0 = ret.Get(0).(VisorData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, cipher.PubKey) error); ok {
		r1 = rf(ctx, netType, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transports provides a mock function with given fields: ctx
func (_m *MockAPIClient) Transports(ctx context.Context) (map[cipher.PubKey][]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Transports")
	}

	var r0 map[cipher.PubKey][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[cipher.PubKey][]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[cipher.PubKey][]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[cipher.PubKey][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAPIClient creates a new instance of MockAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIClient {
	mock := &MockAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
