// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: pkg/visor/rpcgrpc/ping.proto

package rpcgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingService_StreamPing_FullMethodName              = "/rpcgrpc.PingService/StreamPing"
	PingService_StreamDmsgPing_FullMethodName          = "/rpcgrpc.PingService/StreamDmsgPing"
	PingService_StreamBandwidthTest_FullMethodName     = "/rpcgrpc.PingService/StreamBandwidthTest"
	PingService_StreamDmsgBandwidthTest_FullMethodName = "/rpcgrpc.PingService/StreamDmsgBandwidthTest"
)

// PingServiceClient is the client API for PingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PingService provides streaming ping functionality
type PingServiceClient interface {
	// StreamPing performs multiple pings and streams results back one at a time
	StreamPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResult], error)
	// StreamDmsgPing performs multiple pings over dmsg and streams results
	StreamDmsgPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResult], error)
	// StreamBandwidthTest performs a bandwidth test and streams progress
	StreamBandwidthTest(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BandwidthProgress], error)
	// StreamDmsgBandwidthTest performs a bandwidth test over dmsg and streams progress
	StreamDmsgBandwidthTest(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BandwidthProgress], error)
}

type pingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServiceClient(cc grpc.ClientConnInterface) PingServiceClient {
	return &pingServiceClient{cc}
}

func (c *pingServiceClient) StreamPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PingService_ServiceDesc.Streams[0], PingService_StreamPing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PingRequest, PingResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamPingClient = grpc.ServerStreamingClient[PingResult]

func (c *pingServiceClient) StreamDmsgPing(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PingResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PingService_ServiceDesc.Streams[1], PingService_StreamDmsgPing_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PingRequest, PingResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamDmsgPingClient = grpc.ServerStreamingClient[PingResult]

func (c *pingServiceClient) StreamBandwidthTest(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BandwidthProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PingService_ServiceDesc.Streams[2], PingService_StreamBandwidthTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BandwidthRequest, BandwidthProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamBandwidthTestClient = grpc.ServerStreamingClient[BandwidthProgress]

func (c *pingServiceClient) StreamDmsgBandwidthTest(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BandwidthProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PingService_ServiceDesc.Streams[3], PingService_StreamDmsgBandwidthTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BandwidthRequest, BandwidthProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamDmsgBandwidthTestClient = grpc.ServerStreamingClient[BandwidthProgress]

// PingServiceServer is the server API for PingService service.
// All implementations must embed UnimplementedPingServiceServer
// for forward compatibility.
//
// PingService provides streaming ping functionality
type PingServiceServer interface {
	// StreamPing performs multiple pings and streams results back one at a time
	StreamPing(*PingRequest, grpc.ServerStreamingServer[PingResult]) error
	// StreamDmsgPing performs multiple pings over dmsg and streams results
	StreamDmsgPing(*PingRequest, grpc.ServerStreamingServer[PingResult]) error
	// StreamBandwidthTest performs a bandwidth test and streams progress
	StreamBandwidthTest(*BandwidthRequest, grpc.ServerStreamingServer[BandwidthProgress]) error
	// StreamDmsgBandwidthTest performs a bandwidth test over dmsg and streams progress
	StreamDmsgBandwidthTest(*BandwidthRequest, grpc.ServerStreamingServer[BandwidthProgress]) error
	mustEmbedUnimplementedPingServiceServer()
}

// UnimplementedPingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingServiceServer struct{}

func (UnimplementedPingServiceServer) StreamPing(*PingRequest, grpc.ServerStreamingServer[PingResult]) error {
	return status.Error(codes.Unimplemented, "method StreamPing not implemented")
}
func (UnimplementedPingServiceServer) StreamDmsgPing(*PingRequest, grpc.ServerStreamingServer[PingResult]) error {
	return status.Error(codes.Unimplemented, "method StreamDmsgPing not implemented")
}
func (UnimplementedPingServiceServer) StreamBandwidthTest(*BandwidthRequest, grpc.ServerStreamingServer[BandwidthProgress]) error {
	return status.Error(codes.Unimplemented, "method StreamBandwidthTest not implemented")
}
func (UnimplementedPingServiceServer) StreamDmsgBandwidthTest(*BandwidthRequest, grpc.ServerStreamingServer[BandwidthProgress]) error {
	return status.Error(codes.Unimplemented, "method StreamDmsgBandwidthTest not implemented")
}
func (UnimplementedPingServiceServer) mustEmbedUnimplementedPingServiceServer() {}
func (UnimplementedPingServiceServer) testEmbeddedByValue()                     {}

// UnsafePingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingServiceServer will
// result in compilation errors.
type UnsafePingServiceServer interface {
	mustEmbedUnimplementedPingServiceServer()
}

func RegisterPingServiceServer(s grpc.ServiceRegistrar, srv PingServiceServer) {
	// If the following call panics, it indicates UnimplementedPingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingService_ServiceDesc, srv)
}

func _PingService_StreamPing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingServiceServer).StreamPing(m, &grpc.GenericServerStream[PingRequest, PingResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamPingServer = grpc.ServerStreamingServer[PingResult]

func _PingService_StreamDmsgPing_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingServiceServer).StreamDmsgPing(m, &grpc.GenericServerStream[PingRequest, PingResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamDmsgPingServer = grpc.ServerStreamingServer[PingResult]

func _PingService_StreamBandwidthTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BandwidthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingServiceServer).StreamBandwidthTest(m, &grpc.GenericServerStream[BandwidthRequest, BandwidthProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamBandwidthTestServer = grpc.ServerStreamingServer[BandwidthProgress]

func _PingService_StreamDmsgBandwidthTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BandwidthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingServiceServer).StreamDmsgBandwidthTest(m, &grpc.GenericServerStream[BandwidthRequest, BandwidthProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingService_StreamDmsgBandwidthTestServer = grpc.ServerStreamingServer[BandwidthProgress]

// PingService_ServiceDesc is the grpc.ServiceDesc for PingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcgrpc.PingService",
	HandlerType: (*PingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPing",
			Handler:       _PingService_StreamPing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDmsgPing",
			Handler:       _PingService_StreamDmsgPing_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBandwidthTest",
			Handler:       _PingService_StreamBandwidthTest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDmsgBandwidthTest",
			Handler:       _PingService_StreamDmsgBandwidthTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/visor/rpcgrpc/ping.proto",
}
