package com.skycoin.wallet

import com.skycoin.wallet.skycoin.SkycoinCreate
import com.skycoin.wallet.skycoin.SkycoinCrypto
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Byte-for-byte replay of transaction.Create fixtures generated by the Go
 * reference implementation: same inputs chosen in the same order, same hour
 * distribution, same serialization, same inner hash.
 */
class SkycoinCreateFixtureTest {

    @Serializable
    private class UxFixture(
        val hash: String,
        val time: ULong,
        val bkSeq: ULong,
        val srcTx: String,
        val address: String,
        val coins: ULong,
        val hours: ULong,
        val calculatedHours: ULong,
    )

    @Serializable
    private class DestFixture(val address: String, val coins: ULong)

    @Serializable
    private class OutFixture(val address: String, val coins: ULong, val hours: ULong)

    @Serializable
    private class CaseFixture(
        val name: String,
        val uxouts: List<UxFixture>,
        val to: List<DestFixture>,
        val changeAddress: String,
        val burnFactor: UInt,
        val expectedInputs: List<String>,
        val expectedOutputs: List<OutFixture>,
        val expectedInnerHash: String,
        val expectedUnsignedHex: String,
        val expectedLength: UInt,
    )

    @Serializable
    private class WalletFixture(
        val seed: String,
        val addresses: List<String>,
        val secrets: List<String>,
        val publics: List<String>,
    )

    @Serializable
    private class Fixtures(val wallet: WalletFixture, val cases: List<CaseFixture>)

    private val fixtures: Fixtures = Json { ignoreUnknownKeys = true }.decodeFromString(
        Fixtures.serializer(),
        javaClass.getResourceAsStream("/skycoin-fixtures.json")!!.bufferedReader().readText(),
    )

    @Test
    fun walletChainMatches() {
        val keys = SkycoinCrypto.generateKeyPairs(
            fixtures.wallet.seed.toByteArray(Charsets.UTF_8),
            fixtures.wallet.addresses.size,
        )
        keys.forEachIndexed { i, kp ->
            assertEquals(fixtures.wallet.secrets[i], kp.secret.toHex())
            assertEquals(fixtures.wallet.addresses[i], SkycoinCrypto.addressFromPubKey(kp.public))
        }
    }

    @Test
    fun createMatchesReference() {
        for (case in fixtures.cases) {
            val unspents = case.uxouts.map {
                SkycoinCreate.UxBalance(
                    hash = it.hash.hexToBytes(),
                    hashHex = it.hash,
                    bkSeq = it.bkSeq,
                    address = it.address,
                    coins = it.coins,
                    initialHours = it.hours,
                    hours = it.calculatedHours,
                )
            }
            val created = SkycoinCreate.create(
                unspents = unspents,
                to = case.to.map { SkycoinCreate.Destination(it.address, it.coins) },
                changeAddress = case.changeAddress,
                burnFactor = case.burnFactor,
            )

            assertEquals(case.expectedInputs, created.txn.inputs.map { it.toHex() }, "${case.name}: inputs")
            assertEquals(case.expectedOutputs.size, created.txn.outputs.size, "${case.name}: output count")
            case.expectedOutputs.forEachIndexed { i, o ->
                val got = created.txn.outputs[i]
                assertEquals(o.coins, got.coins, "${case.name}: output $i coins")
                assertEquals(o.hours, got.hours, "${case.name}: output $i hours")
                assertEquals(
                    SkycoinCrypto.decodeAddress(o.address)!!.toHex(),
                    got.addressKey.toHex(),
                    "${case.name}: output $i address",
                )
            }
            assertEquals(case.expectedInnerHash, created.txn.hashInner().toHex(), "${case.name}: inner hash")
            assertEquals(case.expectedUnsignedHex, created.txn.serializeHex(), "${case.name}: serialization")
            assertEquals(case.expectedLength.toLong(), created.txn.length, "${case.name}: length")
        }
    }

    @Test
    fun signedTransactionVerifies() {
        val case = fixtures.cases.first()
        val unspents = case.uxouts.map {
            SkycoinCreate.UxBalance(
                hash = it.hash.hexToBytes(),
                hashHex = it.hash,
                bkSeq = it.bkSeq,
                address = it.address,
                coins = it.coins,
                initialHours = it.hours,
                hours = it.calculatedHours,
            )
        }
        val created = SkycoinCreate.create(
            unspents, case.to.map { SkycoinCreate.Destination(it.address, it.coins) },
            case.changeAddress, case.burnFactor,
        )

        val keys = SkycoinCrypto.generateKeyPairs(
            fixtures.wallet.seed.toByteArray(Charsets.UTF_8),
            fixtures.wallet.addresses.size,
        )
        val byAddress = fixtures.wallet.addresses.indices.associate {
            fixtures.wallet.addresses[it] to keys[it]
        }
        val inputKeys = created.txn.inputs.map { uxid ->
            val addr = created.spends.first { it.hash.contentEquals(uxid) }.address
            byAddress.getValue(addr).secret
        }

        created.txn.signInputs(inputKeys)

        // Each signature must recover to the address that owns the spent output.
        created.txn.inputs.forEachIndexed { i, uxid ->
            val hash = Hashes.sha256(created.txn.hashInner(), uxid)
            val recovered = Secp256k1.recoverCompact(hash, created.txn.sigs[i])!!
            val addr = created.spends.first { it.hash.contentEquals(uxid) }.address
            assertEquals(addr, SkycoinCrypto.addressFromPubKey(recovered), "sig $i recovers to owner")
        }

        // Signing must not disturb the priced structure.
        assertEquals(case.expectedInnerHash, created.txn.hashInner().toHex())
        assertTrue(created.txn.serializeHex().length == case.expectedUnsignedHex.length)
    }
}
