// Package skynetca pkg/skynetca/leaf.go c4-app-skynet
package skynetca

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"errors"
	"fmt"
	"math/big"
	"strings"
	"sync"
	"time"
)

// LeafMinter mints (and typically caches) leaf TLS certs signed by
// a local CA. Implementations must be safe for concurrent use.
type LeafMinter interface {
	For(host string) (*tls.Certificate, error)
}

// HostPermitter is optionally implemented by a LeafMinter to report — WITHOUT
// attempting a mint — whether it can issue a leaf for host. Callers that decide
// whether to route a request down the TLS-MITM path (e.g. the resolving proxies'
// HTTPS interstitial) use this to skip hosts the name-constrained CA can't cover
// (arbitrary clearnet HTTPS), rather than calling For and logging its expected
// "does not match any permitted suffix" failure on every such request.
type HostPermitter interface {
	Permits(host string) bool
}

// Permits reports whether m can mint a leaf for host. A LeafMinter that
// implements HostPermitter is asked directly; any other implementation is
// treated optimistically (the mint itself still enforces its constraints). This
// keeps the check non-breaking — LeafMinter itself is unchanged.
func Permits(m LeafMinter, host string) bool {
	if hp, ok := m.(HostPermitter); ok {
		return hp.Permits(host)
	}
	return m != nil
}

// LeafOptions configures a CachedMinter.
type LeafOptions struct {
	Validity          time.Duration
	RenewBefore       time.Duration
	PermittedSuffixes []string
}

func (o LeafOptions) withDefaults(ca *x509.Certificate) LeafOptions {
	if o.Validity == 0 {
		o.Validity = 7 * 24 * time.Hour
	}
	if o.RenewBefore == 0 {
		o.RenewBefore = 24 * time.Hour
	}
	if len(o.PermittedSuffixes) == 0 {
		// Mirror the CA's nameConstraints by default; the browser
		// will reject any leaf whose DNS name escapes this set
		// regardless of what the minter does, so it's the right
		// source of truth.
		o.PermittedSuffixes = append([]string{}, ca.PermittedDNSDomains...)
	}
	return o
}

// NewMinter constructs a CachedMinter that signs leaves with the
// given CA. The CA must have been generated by GenerateCA (or be
// otherwise compatible — IsCA, KeyUsage with CertSign, name
// constraints set).
func NewMinter(ca *x509.Certificate, caKey *ecdsa.PrivateKey, opts LeafOptions) *CachedMinter {
	return &CachedMinter{
		ca:    ca,
		caKey: caKey,
		opts:  opts.withDefaults(ca),
		cache: map[string]*tls.Certificate{},
	}
}

// CachedMinter is the default LeafMinter implementation. Leaves are
// regenerated on cache miss and when the cached cert's remaining
// lifetime falls below opts.RenewBefore.
type CachedMinter struct {
	ca    *x509.Certificate
	caKey *ecdsa.PrivateKey
	opts  LeafOptions

	mu    sync.Mutex
	cache map[string]*tls.Certificate
}

// For returns a leaf cert valid for host. The returned cert is
// shared with other callers via the cache; do not mutate.
func (m *CachedMinter) For(host string) (*tls.Certificate, error) {
	if !m.permitted(host) {
		return nil, fmt.Errorf("skynetca: host %q does not match any permitted suffix %v", host, m.opts.PermittedSuffixes)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.cache[host]; ok && m.fresh(c) {
		return c, nil
	}
	fresh, err := m.mint(host)
	if err != nil {
		return nil, err
	}
	m.cache[host] = fresh
	return fresh, nil
}

func (m *CachedMinter) fresh(c *tls.Certificate) bool {
	leaf := c.Leaf
	if leaf == nil && len(c.Certificate) > 0 {
		if parsed, err := x509.ParseCertificate(c.Certificate[0]); err == nil {
			leaf = parsed
		}
	}
	return leaf != nil && time.Until(leaf.NotAfter) > m.opts.RenewBefore
}

// Permits implements HostPermitter: it reports whether host falls under one of
// this minter's permitted suffixes, without minting or caching anything.
func (m *CachedMinter) Permits(host string) bool { return m.permitted(host) }

func (m *CachedMinter) permitted(host string) bool {
	for _, suf := range m.opts.PermittedSuffixes {
		// Subdomain semantics: the suffix matches when host ends
		// with it AND has at least one label before it.
		if strings.HasSuffix(host, suf) && len(host) > len(suf) {
			return true
		}
	}
	return false
}

func (m *CachedMinter) mint(host string) (*tls.Certificate, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate leaf key: %w", err)
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 159))
	if err != nil {
		return nil, fmt.Errorf("generate serial: %w", err)
	}

	now := time.Now().UTC()
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		// Subject.CommonName intentionally omitted. X.520
		// ub-common-name caps it at 64 chars; a skynet host like
		// "<subdomain>.<53-char-base32-pk>.skynet" easily exceeds
		// that when the subdomain is non-trivial (e.g.
		// "magnetosphere.net.<53>.skynet" = 78 chars). Strict
		// X.509 parsers reject the cert outright. Browsers have
		// ignored CN since 2017 (Chrome) / Firefox followed —
		// SAN is the source of truth.
		Subject:     pkix.Name{},
		DNSNames:    []string{host},
		NotBefore:   now.Add(-1 * time.Hour),
		NotAfter:    now.Add(m.opts.Validity),
		KeyUsage:    x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, m.ca, &key.PublicKey, m.caKey)
	if err != nil {
		return nil, fmt.Errorf("sign leaf: %w", err)
	}
	leaf, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, fmt.Errorf("parse leaf: %w", err)
	}
	// Include the CA in the cert chain so a browser that hasn't
	// yet been told about an intermediary still sees a complete chain.
	return &tls.Certificate{
		Certificate: [][]byte{der, m.ca.Raw},
		PrivateKey:  key,
		Leaf:        leaf,
	}, nil
}

// staticMinter is a non-caching LeafMinter that always returns the
// same leaf. Intended for tests.
type staticMinter struct{ leaf *tls.Certificate }

// NewStaticMinter returns a LeafMinter that always returns leaf.
// Intended for tests; production callers should use NewMinter.
func NewStaticMinter(leaf *tls.Certificate) LeafMinter { return staticMinter{leaf} }

func (s staticMinter) For(_ string) (*tls.Certificate, error) {
	if s.leaf == nil {
		return nil, errors.New("skynetca: nil static leaf")
	}
	return s.leaf, nil
}

// Permits implements HostPermitter: a static minter serves any host (it holds a
// single fixed leaf), provided it has one.
func (s staticMinter) Permits(_ string) bool { return s.leaf != nil }
