#!/usr/bin/env bash

set -euo pipefail

mkdir -p /tmp/skywire
mkdir -p /Users/"${USER}"/Library/Application\ Support/Skywire

if [[ ! -d "$HOME"/Library/Logs/skywire ]]; then
  mkdir -p "$HOME"/Library/Logs/skywire
fi
