#!/usr/bin/env bash

set -euo pipefail

mkdir -p /tmp/skywire
mkdir -p /Users/"${USER}"/Library/Application\ Support/Skywire

if [[ ! -d /Users/"${USER}"/Library/Logs/skywire ]]; then
  mkdir -p /Users/"${USER}"/Library/Logs/skywire
  sudo chown -R /Users/"${USER}"/Library/Logs/skywire
fi
