// Code generated by deployment/cmd/gen; DO NOT EDIT.

//go:build js

// Package deployment pkg/deployment/data_static_js.go
//
// Static-data variant of the prod / test deployment bundles. The
// non-WASM build path (config_native.go) populates deployment.Prod
// / Test by unmarshalling the embedded services-config.json at
// init time; that drags encoding/json and the reflect runtime
// helpers TinyGo can't link. Under js/wasm we use these literals
// instead — config_js.go's init copies them into the public vars.
//
// Regenerate after editing services-config.json:
//
//	go generate ./deployment/
package deployment

import (
	"github.com/skycoin/skywire/pkg/cipher"
)

var prodData = Services{
	DmsgDiscovery:      "http://dmsgd.skywire.skycoin.com",
	TransportDiscovery: "http://tpd.skywire.skycoin.com",
	AddressResolver:    "http://ar.skywire.skycoin.com",
	RouteFinder:        "http://rf.skywire.skycoin.com",
	RouteSetupNodes: []cipher.PubKey{
		mustPubKey("0324579f003e6b4048bae2def4365e634d8e0e3054a20fc7af49daf2a179658557"),
		mustPubKey("024fbd3997d4260f731b01abcfce60b8967a6d4c6a11d1008812810ea1437ce438"),
	},
	TransportSetupPKs: []cipher.PubKey{
		mustPubKey("03530b786c670fc7f5ab9021478c7ec9cd06a03f3ea1416c50c4a8889ef5bba80e"),
		mustPubKey("03271c0de223b80400d9bd4b7722b536a245eb6c9c3176781ee41e7bac8f9bad21"),
		mustPubKey("03a792e6d960c88c6fb2184ee4f16714c58b55f0746840617a19f7dd6e021699d9"),
		mustPubKey("0313efedc579f57f05d4f5bc3fbf0261f31e51cdcfde7e568169acf92c78868926"),
		mustPubKey("025c7bbf23e3441a36d7e8a1e9d717921e2a49a2ce035680fec4808a048d244c8a"),
		mustPubKey("030eb6967f6e23e81db0d214f925fc5ce3371e1b059fb8379ae3eb1edfc95e0b46"),
		mustPubKey("02e582c0a5e5563aad47f561b272e4c3a9f7ac716258b58e58eb50afd83c286a7f"),
		mustPubKey("02ddc6c749d6ed067bb68df19c9bcb1a58b7587464043b1707398ffa26a9746b26"),
		mustPubKey("03aa0b1c4e23616872058c11c6efba777c130a85eaf909945d697399a1eb08426d"),
		mustPubKey("03adb2c924987d8deef04d02bd95236c5ae172fe5dfe7273e0461d96bf4bc220be"),
	},
	UptimeTracker:    "http://ut.skywire.skycoin.com",
	ServiceDiscovery: "http://sd.skycoin.com",
	StunServers: []string{
		"139.162.160.227:3478",
		"172.104.247.120:3478",
	},
	DNSServer: "1.1.1.1",
	GeoIP:     "http://ip.skycoin.com",
	SurveyWhitelist: []cipher.PubKey{
		mustPubKey("02b5ee5333aa6b7f5fc623b7d5f35f505cb7f974e98a70751cf41962f84c8c4637"),
		mustPubKey("03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3"),
		mustPubKey("020d35bbaf0a5abc8ec0ba33cde219fde734c63e7202098e1f9a6cf9daaeee55a9"),
		mustPubKey("027f7dec979482f418f01dfabddbd750ad036c579a16422125dd9a313eaa59c8e1"),
		mustPubKey("031d4cf1b7ab4c789b56c769f2888e4a61c778dfa5fe7e5cd0217fc41660b2eb65"),
		mustPubKey("0327e2cf1d2e516ecbfdbd616a87489cc92a73af97335d5c8c29eafb5d8882264a"),
		mustPubKey("03abbb3eff140cf3dce468b3fa5a28c80fa02c6703d7b952be6faaf2050990ebf4"),
	},
	ConfDmsg: "dmsg://021f751cb8690a96585e10c4d253513cd208bd659fd4f6c227ad49d2b75eec1ff2:80",
	DmsgServers: []DmsgServerEntry{
		{Static: "0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.160.227:30086"}},
		{Static: "0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13", Server: struct {
			Address string `json:"address"`
		}{Address: "45.79.213.251:30087"}},
		{Static: "02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0", Server: struct {
			Address string `json:"address"`
		}{Address: "143.42.59.213:30081"}},
		{Static: "0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7", Server: struct {
			Address string `json:"address"`
		}{Address: "70.121.13.123:9082"}},
		{Static: "02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.173.101:30082"}},
		{Static: "03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.173.101:30083"}},
	},
	DmsgDiscoveryDmsg:      "dmsg://022e607e0914d6e7ccda7587f95790c09e126bbd506cc476a1eda852325aadd1aa:80",
	TransportDiscoveryDmsg: "dmsg://02b307aee5c8ce1666c63891f8af25ad2f0a47a243914c963942b3ba35b9d095ae:80",
	AddressResolverDmsg:    "dmsg://03234b2ee4128d1f78c180d06911102906c80795dfe41bd6253f2619c8b6252a02:80",
	RouteFinderDmsg:        "dmsg://039d89c5eedfda4a28b0c58b0b643eff949f08e4f68c8357278081d26f5a592d74:80",
	UptimeTrackerDmsg:      "dmsg://022c424caa6239ba7d1d9d8f7dab56cd5ec6ae2ea9ad97bb94ad4b48f62a540d3f:80",
	ServiceDiscoveryDmsg:   "dmsg://0204890f9def4f9a5448c2e824c6a4afc85fd1f877322320898fafdf407cc6fef7:80",
	RewardSystem:           "https://theskywirenetwork.net",
	RewardSystemDmsg:       "dmsg://036a70e6956061778e1883e928c1236189db14dfd446df23d83e45c321b330c91f:80",
}

var testData = Services{
	DmsgDiscovery:      "http://dmsgd.skywire.dev",
	TransportDiscovery: "http://tpd.skywire.dev",
	AddressResolver:    "http://ar.skywire.dev",
	RouteFinder:        "http://rf.skywire.dev",
	RouteSetupNodes: []cipher.PubKey{
		mustPubKey("0324579f003e6b4048bae2def4365e634d8e0e3054a20fc7af49daf2a179658557"),
		mustPubKey("024fbd3997d4260f731b01abcfce60b8967a6d4c6a11d1008812810ea1437ce438"),
	},
	TransportSetupPKs: []cipher.PubKey{
		mustPubKey("03530b786c670fc7f5ab9021478c7ec9cd06a03f3ea1416c50c4a8889ef5bba80e"),
		mustPubKey("03271c0de223b80400d9bd4b7722b536a245eb6c9c3176781ee41e7bac8f9bad21"),
		mustPubKey("03a792e6d960c88c6fb2184ee4f16714c58b55f0746840617a19f7dd6e021699d9"),
		mustPubKey("0313efedc579f57f05d4f5bc3fbf0261f31e51cdcfde7e568169acf92c78868926"),
		mustPubKey("025c7bbf23e3441a36d7e8a1e9d717921e2a49a2ce035680fec4808a048d244c8a"),
		mustPubKey("030eb6967f6e23e81db0d214f925fc5ce3371e1b059fb8379ae3eb1edfc95e0b46"),
		mustPubKey("02e582c0a5e5563aad47f561b272e4c3a9f7ac716258b58e58eb50afd83c286a7f"),
		mustPubKey("02ddc6c749d6ed067bb68df19c9bcb1a58b7587464043b1707398ffa26a9746b26"),
		mustPubKey("03aa0b1c4e23616872058c11c6efba777c130a85eaf909945d697399a1eb08426d"),
		mustPubKey("03adb2c924987d8deef04d02bd95236c5ae172fe5dfe7273e0461d96bf4bc220be"),
	},
	UptimeTracker:    "http://ut.skywire.dev",
	ServiceDiscovery: "http://sd.skywire.dev",
	StunServers: []string{
		"139.162.160.227:3478",
		"172.104.247.120:3478",
	},
	DNSServer: "1.1.1.1",
	GeoIP:     "http://ip.skywire.dev",
	SurveyWhitelist: []cipher.PubKey{
		mustPubKey("02b5ee5333aa6b7f5fc623b7d5f35f505cb7f974e98a70751cf41962f84c8c4637"),
		mustPubKey("03714c8bdaee0fb48f47babbc47c33e1880752b6620317c9d56b30f3b0ff58a9c3"),
		mustPubKey("020d35bbaf0a5abc8ec0ba33cde219fde734c63e7202098e1f9a6cf9daaeee55a9"),
		mustPubKey("027f7dec979482f418f01dfabddbd750ad036c579a16422125dd9a313eaa59c8e1"),
		mustPubKey("031d4cf1b7ab4c789b56c769f2888e4a61c778dfa5fe7e5cd0217fc41660b2eb65"),
		mustPubKey("0327e2cf1d2e516ecbfdbd616a87489cc92a73af97335d5c8c29eafb5d8882264a"),
		mustPubKey("03abbb3eff140cf3dce468b3fa5a28c80fa02c6703d7b952be6faaf2050990ebf4"),
	},
	ConfDmsg: "dmsg://021f751cb8690a96585e10c4d253513cd208bd659fd4f6c227ad49d2b75eec1ff2:80",
	DmsgServers: []DmsgServerEntry{
		{Static: "0281a102c82820e811368c8d028cf11b1a985043b726b1bcdb8fce89b27384b2cb", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.160.227:30086"}},
		{Static: "0371ab4bcff7b121f4b91f6856d6740c6f9dc1fe716977850aeb5d84378b300a13", Server: struct {
			Address string `json:"address"`
		}{Address: "45.79.213.251:30087"}},
		{Static: "02a49bc0aa1b5b78f638e9189be4ed095bac5d6839c828465a8350f80ac07629c0", Server: struct {
			Address string `json:"address"`
		}{Address: "143.42.59.213:30081"}},
		{Static: "0326978f5a53aff537dbb47fed58b1f123af3b00132d365f1309a14db4168dcff7", Server: struct {
			Address string `json:"address"`
		}{Address: "70.121.13.123:9082"}},
		{Static: "02a2d4c346dabd165fd555dfdba4a7f4d18786fe7e055e562397cd5102bdd7f8dd", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.173.101:30082"}},
		{Static: "03717576ada5b1744e395c66c2bb11cea73b0e23d0dcd54422139b1a7f12e962c4", Server: struct {
			Address string `json:"address"`
		}{Address: "139.162.173.101:30083"}},
	},
	DmsgDiscoveryDmsg:      "dmsg://022e607e0914d6e7ccda7587f95790c09e126bbd506cc476a1eda852325aadd1aa:80",
	TransportDiscoveryDmsg: "dmsg://02b307aee5c8ce1666c63891f8af25ad2f0a47a243914c963942b3ba35b9d095ae:80",
	AddressResolverDmsg:    "dmsg://03234b2ee4128d1f78c180d06911102906c80795dfe41bd6253f2619c8b6252a02:80",
	RouteFinderDmsg:        "dmsg://039d89c5eedfda4a28b0c58b0b643eff949f08e4f68c8357278081d26f5a592d74:80",
	UptimeTrackerDmsg:      "dmsg://022c424caa6239ba7d1d9d8f7dab56cd5ec6ae2ea9ad97bb94ad4b48f62a540d3f:80",
	ServiceDiscoveryDmsg:   "dmsg://0204890f9def4f9a5448c2e824c6a4afc85fd1f877322320898fafdf407cc6fef7:80",
	RewardSystem:           "https://theskywirenetwork.net",
	RewardSystemDmsg:       "dmsg://036a70e6956061778e1883e928c1236189db14dfd446df23d83e45c321b330c91f:80",
}

var prodConfData = Conf{Conf: "http://conf.skywire.skycoin.com"}
var testConfData = Conf{Conf: "http://conf.skywire.dev"}
