// Package visor pkg/visor/proxy_default_api.go
//
// Generated by /tmp/gen_proxy_stubs.go from pkg/visor/api.go.
//
// proxyDefaultAPI implements the full API interface by returning
// ErrProxyNotSupported (or the zero value for non-error returns)
// from every method. proxiedVisorAPI embeds it and overrides the
// methods that have HVxxx counterparts on the sub-hypervisor's API.
//
// To regenerate after API changes:
//
//	go run /tmp/gen_proxy_stubs.go > pkg/visor/proxy_default_api.go
package visor

import (
	"encoding/json"
	"net"
	"time"

	"github.com/google/uuid"

	"github.com/skycoin/skywire/pkg/app/appcommon"
	"github.com/skycoin/skywire/pkg/app/appnet"
	"github.com/skycoin/skywire/pkg/app/appserver"
	"github.com/skycoin/skywire/pkg/cipher"
	"github.com/skycoin/skywire/pkg/dmsg/dmsgpty"
	"github.com/skycoin/skywire/pkg/netutil"
	"github.com/skycoin/skywire/pkg/router/setupmetrics"
	"github.com/skycoin/skywire/pkg/routing"
	"github.com/skycoin/skywire/pkg/servicedisc"
	"github.com/skycoin/skywire/pkg/transport"
	"github.com/skycoin/skywire/pkg/visor/dmsgtracker"
	"github.com/skycoin/skywire/pkg/visor/logserver"
	"github.com/skycoin/skywire/pkg/visor/visorconfig"
)

// Suppress unused-import warnings if a particular method set
// doesn't reference all packages — the imports above are scoped to
// the full surface area of api.go.
var _ = json.RawMessage(nil)
var _ net.Conn
var _ time.Duration
var _ uuid.UUID
var _ appcommon.LogStore
var _ = appnet.Addr{}
var _ appserver.AppState
var _ cipher.PubKey
var _ dmsgpty.CommandExecResult
var _ netutil.EphemeralDiagResult
var _ setupmetrics.Metrics
var _ routing.Rule
var _ servicedisc.Service
var _ transport.Entry
var _ dmsgtracker.DmsgClientSummary
var _ logserver.ServiceEntry
var _ visorconfig.Duration

type proxyDefaultAPI struct{}

func (proxyDefaultAPI) Overview() (*Overview, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Summary() (*Summary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Health() (*HealthInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) IsStartupComplete() bool {
	return false
}

func (proxyDefaultAPI) EnableHypervisor() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DisableHypervisor() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) EnableHypervisorPersist(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DisableHypervisorPersist(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) IsHypervisorEnabled() bool {
	return false
}

func (proxyDefaultAPI) Uptime() (float64, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) UptimeHistory(_ UptimeHistoryArgs) (*UptimeHistoryResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RuntimeStats() (*RuntimeStatsInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Reload() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) Shutdown() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RuntimeLogs() (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) RuntimeLogsSince(_ int64) (RuntimeLogsDelta, error) {
	return RuntimeLogsDelta{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) HostStats() (*HostStatsInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) NetworkView() (*NetworkViewResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SkychatPasswordIsSet() (bool, error) {
	return false, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetSkychatPassword(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ClearSkychatPassword(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SkychatLocalAddr() (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoteVisors() ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPtyExec(_ DmsgPtyExecArgs) (*dmsgpty.CommandExecResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetLogRotationInterval() (visorconfig.Duration, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetLogRotationInterval(_ visorconfig.Duration) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) IsDMSGClientReady() (bool, error) {
	return false, ErrProxyNotSupported
}

func (proxyDefaultAPI) DMSGServers() ([]DMSGServerInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Ports() (map[string]PortDetail, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetRewardAddress(_ string) (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) GetRewardAddress() (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) DeleteRewardAddress() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetLANDmsgServer(_ LANDmsgServerInfo) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) App(_ string) (*appserver.AppState, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Apps() ([]*appserver.AppState, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) StartApp(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StartAppWithMode(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) AddApp(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DeleteApp(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RegisterApp(_ appcommon.ProcConfig) (appcommon.ProcKey, error) {
	return appcommon.ProcKey{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) DeregisterApp(_ appcommon.ProcKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopApp(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) KillApp(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppDetailedStatus(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppError(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RestartApp(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAutoStart(_ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppWhitelist(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppPK(_ string, _ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppSecure(_ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppAddress(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppKillswitch(_ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppNetworkInterface(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppDNS(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DoCustomSetting(_ string, _ map[string]any) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppArgs(_ string, _ []string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppEnv(_ string, _ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppEnvBatch(_ string, _ map[string]string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppEnvFull(_ string, _ []string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetAppLauncherMode(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) AppHelp(_ string) (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) LogsSince(_ time.Time, _ string) ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetAppStats(_ string) (appserver.AppStats, error) {
	return appserver.AppStats{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetAppError(_ string) (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) GetAppConnectionsSummary(_ string) ([]appserver.ConnectionSummary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) StartVPNClient(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StartVPNClientWithMode(_ cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopVPNClient(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) VPNServers(_ string, _ string) ([]servicedisc.Service, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) StartSkysocksClient(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopSkysocksClients() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ProxyServers(_ string, _ string) ([]servicedisc.Service, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TestProxy(_ ProxyTestConfig) ([]ProxyTestResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetExistingTPOnly(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetForceLocalRoutes(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetMuxRoutes(_ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetRouterSettings() (RouterSettings, error) {
	return RouterSettings{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetRouterSettings(_ RouterSettings) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetMuxMode(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) TransportTypes() ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Transports(_ []string, _ []cipher.PubKey, _ bool) ([]*TransportSummary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) Transport(_ uuid.UUID) (*TransportSummary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) AddTransport(_ cipher.PubKey, _ string, _ time.Duration, _ string, _ bool, _ bool) (*TransportSummary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetSTCPAddr(_ cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveTransport(_ uuid.UUID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveAllTransports() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetPublicAutoconnect(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetIsPublic(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetIsPublic() bool {
	return false
}

func (proxyDefaultAPI) GetRuntimeConfig() ([]byte, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetRuntimeConfig(_ []byte) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) LocalTransportStats() (*LocalTransportStatsResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) LocalUptimeStats(_ LocalUptimeArgs) (*LocalUptimeResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) FetchCXO(_ FetchCXOArgs) (*FetchCXOResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) CXOStatus() ([]FeedStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) CXORefreshFeed(_ CXORefreshArgs) (*FeedStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetConfigPath() (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) StartPublicAutoconnect() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopPublicAutoconnect() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) PublicAutoconnectStatus() (bool, error) {
	return false, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetPersistentTransports() ([]transport.PersistentTransports, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetPersistentTransports(_ []transport.PersistentTransports) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetTransportLogs(_ int) ([]TransportLogEntry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DiscoverTransportsByPK(_ cipher.PubKey) ([]*transport.Entry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DiscoverTransportByID(_ uuid.UUID) (*transport.Entry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RoutingRules() ([]routing.Rule, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RoutingRule(_ routing.RouteID) (routing.Rule, error) {
	return routing.Rule{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) SaveRoutingRule(_ routing.Rule) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveRoutingRule(_ routing.RouteID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RouteGroups() ([]RouteGroupInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RouteGroupMuxInfo(_ string) ([]MuxRouteGroupInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) ActiveRoutes() ([]AppRouteStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) AddMuxRoute(_ string, _ []routing.Hop, _ []routing.Hop, _ uint16) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveMuxRoute(_ string, _ uuid.UUID, _ uint16) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ServiceHealth() ([]ServiceHealthEntry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) FetchServiceData(_ string, _ string) ([]byte, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetMinHops(_ uint16) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetMinHops() (uint16, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetCalculateRoutes(_ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetCalculateRoutes() (bool, error) {
	return false, ErrProxyNotSupported
}

func (proxyDefaultAPI) RegisterTCPPort(_ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DeregisterTCPPort(_ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ListTCPPorts() ([]int, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RegisterForwardedPort(_ ForwardedPort) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) UpdateForwardedPort(_ ForwardedPort) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ListForwardedPorts() ([]ForwardedPort, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) ConnectRawTCP(_ string, _ cipher.PubKey, _ int, _ int) (uuid.UUID, error) {
	return uuid.UUID{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) DisconnectRawTCP(_ uuid.UUID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ListRawTCP() (map[uuid.UUID]*appnet.RawTCPForwardConn, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DialPing(_ PingConfig) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) Ping(_ PingConfig) ([]time.Duration, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) PingOnce(_ PingConfig) (time.Duration, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) StopPing(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopAllPings() (int, []string, error) {
	return 0, nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DialDmsgPing(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DialDmsgPingViaServer(_ cipher.PubKey, _ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) DialDmsgRPC(_ cipher.PubKey) (net.Conn, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPing(_ PingConfig) ([]time.Duration, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPingOnce(_ PingConfig) (time.Duration, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) StopDmsgPing(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GetDmsgPingServerPK(_ cipher.PubKey) (cipher.PubKey, error) {
	return cipher.PubKey{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetRemoteDmsgServers(_ cipher.PubKey) ([]cipher.PubKey, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetPreferredDmsgServer(_ cipher.PubKey) (cipher.PubKey, error) {
	return cipher.PubKey{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) BandwidthTest(_ BandwidthTestConfig) (BandwidthResult, error) {
	return BandwidthResult{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgBandwidthTest(_ BandwidthTestConfig) (BandwidthResult, error) {
	return BandwidthResult{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) TestVisor(_ PingConfig) ([]TestResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) ReinitiateModule(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) FetchUptimeTrackerData(_ string) ([]byte, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DeregisterService(_ []cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StartUIServer(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) StopUIServer() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) UIServerStatus() (*UIServerStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgProbe(_ cipher.PubKey, _ uint16) (bool, error) {
	return false, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgHTTP(_ DmsgHTTPRequest) (*DmsgHTTPResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SkynetHTTP(_ SkynetHTTPRequest) (*SkynetHTTPResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) VisorSCP(_ VisorSCPRequest) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) VisorCat(_ VisorCatRequest) (*VisorCatResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgConnectAll() (*DmsgConnectAllResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetDmsgSessionsCount(_ int) (*DmsgConnectAllResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgSessions() (*DmsgClientSessions, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RegisterCXOFeed(_ string, _ uint16, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) UnregisterCXOFeed(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ListCXOFeeds() []logserver.CXOFeedEntry {
	return nil
}

func (proxyDefaultAPI) PairAdd(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) PairList() ([]PairInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) PairRemove(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) PairMarkActive(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) PairSend(_ cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) PairPoll(_ time.Time) ([]PairMessage, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupCreate(_ GroupCreateArgs) (GroupInfo, string, error) {
	return GroupInfo{}, "", ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupJoin(_ GroupJoinArgs) (GroupInfo, error) {
	return GroupInfo{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupList() ([]GroupInfo, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupGet(_ string) (GroupInfo, error) {
	return GroupInfo{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupInvite(_ string) (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupAddMember(_ string, _ cipher.PubKey) (GroupInfo, error) {
	return GroupInfo{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupPromoteAdmin(_ string, _ cipher.PubKey) (GroupInfo, error) {
	return GroupInfo{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupDemoteAdmin(_ string, _ cipher.PubKey) (GroupInfo, error) {
	return GroupInfo{}, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupSend(_ GroupSendArgs) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupPoll(_ time.Time) ([]GroupMessage, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupDelete(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupLeave(_ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupHistory(_ string, _ int) ([]GroupMessage, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GroupHistoryGroups() ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSStatus() (*TPSStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSAddTransport(_ cipher.PubKey, _ cipher.PubKey, _ string) (*TPSTransportResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSRemoveTransport(_ cipher.PubKey, _ uuid.UUID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSGetTransports(_ cipher.PubKey) ([]TPSTransportResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetTransportSetupNodes() ([]cipher.PubKey, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetTransportSetupNodesSorted() ([]cipher.PubKey, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetRouteSetupNodesSorted() ([]cipher.PubKey, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetTPSHealth() ([]NodeHealth, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) GetRSNHealth() ([]NodeHealth, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) RouteSetupStats() (*setupmetrics.StatsSnapshot, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) EmbeddedProxies() (*EmbeddedProxiesStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetEmbeddedProxyEnabled(_ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) SetEmbeddedProxyUpstream(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) ResetRouteSetupStats() error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSExternalHealthCheck(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSExternalAddTransport(_ cipher.PubKey, _ cipher.PubKey, _ cipher.PubKey, _ string) (*TPSTransportResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TPSExternalGetTransports(_ cipher.PubKey, _ cipher.PubKey) ([]TPSTransportResponse, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPorterStats() (*DmsgPorterStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPorterReset() (*DmsgPorterStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgPorterDiag() (*netutil.EphemeralDiagResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgReconnect() (int, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) DmsgSetMinSessions(_ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) AddHypervisor(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveHypervisor(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) RemoveAllHypervisors() (int, error) {
	return 0, ErrProxyNotSupported
}

func (proxyDefaultAPI) SetHypervisorPassword(_ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) CheckAREntry(_ string) ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) ARSelfInfo() (*ARSelfRegistration, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) TransportRPCCall(_ cipher.PubKey, _ string, _ json.RawMessage) (json.RawMessage, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVListVisors() ([]HVVisorEntry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVListDirectVisors() ([]HVVisorEntry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVListVisorsTree() (*HVVisorTree, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVVisorSummary(_ cipher.PubKey) (*Summary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVStartApp(_ cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVStopApp(_ cipher.PubKey, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetMinHops(_ cipher.PubKey, _ uint16) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetRewardAddress(_ cipher.PubKey, _ string) (string, error) {
	return "", ErrProxyNotSupported
}

func (proxyDefaultAPI) HVRemoveTransport(_ cipher.PubKey, _ uuid.UUID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVRemoveRoutingRule(_ cipher.PubKey, _ routing.RouteID) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVAddTransport(_ cipher.PubKey, _ cipher.PubKey, _ string, _ string, _ time.Duration) (*TransportSummary, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetPublicAutoconnect(_ cipher.PubKey, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetMuxRoutes(_ cipher.PubKey, _ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetCalculateRoutes(_ cipher.PubKey, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVReload(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVShutdown(_ cipher.PubKey) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVServiceHealth(_ cipher.PubKey) ([]ServiceHealthEntry, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVDmsgSessions(_ cipher.PubKey) (*DmsgClientSessions, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVDmsgConnectAll(_ cipher.PubKey) (*DmsgConnectAllResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetDmsgSessionsCount(_ cipher.PubKey, _ int) (*DmsgConnectAllResult, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVLogsSince(_ cipher.PubKey, _ time.Time, _ string) ([]string, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetAutoStart(_ cipher.PubKey, _ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVEmbeddedProxies(_ cipher.PubKey) (*EmbeddedProxiesStatus, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetEmbeddedProxyEnabled(_ cipher.PubKey, _ string, _ bool) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVSetEmbeddedProxyUpstream(_ cipher.PubKey, _ string, _ string) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVListTCPPorts(_ cipher.PubKey) ([]int, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVRegisterTCPPort(_ cipher.PubKey, _ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVDeregisterTCPPort(_ cipher.PubKey, _ int) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVListForwardedPorts(_ cipher.PubKey) ([]ForwardedPort, error) {
	return nil, ErrProxyNotSupported
}

func (proxyDefaultAPI) HVRegisterForwardedPort(_ cipher.PubKey, _ ForwardedPort) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) HVUpdateForwardedPort(_ cipher.PubKey, _ ForwardedPort) error {
	return ErrProxyNotSupported
}

func (proxyDefaultAPI) Close() error {
	return ErrProxyNotSupported
}
