// Code generated by mockery v2.52.3. DO NOT EDIT.

package appnet

import (
	context "context"

	cipher "github.com/skycoin/skywire/pkg/skywire-utilities/pkg/cipher"

	mock "github.com/stretchr/testify/mock"

	net "net"
)

// MockNetworker is an autogenerated mock type for the Networker type
type MockNetworker struct {
	mock.Mock
}

// Dial provides a mock function with given fields: addr
func (_m *MockNetworker) Dial(addr Addr) (net.Conn, error) {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(Addr) (net.Conn, error)); ok {
		return rf(addr)
	}
	if rf, ok := ret.Get(0).(func(Addr) net.Conn); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(Addr) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DialContext provides a mock function with given fields: ctx, addr
func (_m *MockNetworker) DialContext(ctx context.Context, addr Addr) (net.Conn, error) {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for DialContext")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Addr) (net.Conn, error)); ok {
		return rf(ctx, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Addr) net.Conn); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Addr) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Listen provides a mock function with given fields: addr
func (_m *MockNetworker) Listen(addr Addr) (net.Listener, error) {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 net.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(Addr) (net.Listener, error)); ok {
		return rf(addr)
	}
	if rf, ok := ret.Get(0).(func(Addr) net.Listener); ok {
		r0 = rf(addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(Addr) error); ok {
		r1 = rf(addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListenContext provides a mock function with given fields: ctx, addr
func (_m *MockNetworker) ListenContext(ctx context.Context, addr Addr) (net.Listener, error) {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for ListenContext")
	}

	var r0 net.Listener
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Addr) (net.Listener, error)); ok {
		return rf(ctx, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Addr) net.Listener); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Listener)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Addr) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: pk, addr
func (_m *MockNetworker) Ping(pk cipher.PubKey, addr Addr) (net.Conn, error) {
	ret := _m.Called(pk, addr)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(cipher.PubKey, Addr) (net.Conn, error)); ok {
		return rf(pk, addr)
	}
	if rf, ok := ret.Get(0).(func(cipher.PubKey, Addr) net.Conn); ok {
		r0 = rf(pk, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(cipher.PubKey, Addr) error); ok {
		r1 = rf(pk, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PingContext provides a mock function with given fields: ctx, pk, addr
func (_m *MockNetworker) PingContext(ctx context.Context, pk cipher.PubKey, addr Addr) (net.Conn, error) {
	ret := _m.Called(ctx, pk, addr)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cipher.PubKey, Addr) (net.Conn, error)); ok {
		return rf(ctx, pk, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cipher.PubKey, Addr) net.Conn); ok {
		r0 = rf(ctx, pk, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cipher.PubKey, Addr) error); ok {
		r1 = rf(ctx, pk, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNetworker creates a new instance of MockNetworker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworker {
	mock := &MockNetworker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
