// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Autoconnector is an autogenerated mock type for the Autoconnector type
type Autoconnector struct {
	mock.Mock
}

// Run provides a mock function with given fields: _a0
func (_m *Autoconnector) Run(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAutoconnector creates a new instance of Autoconnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoconnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Autoconnector {
	mock := &Autoconnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
