// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	rfclient "github.com/skycoin/skywire/pkg/routefinder/rfclient"
	mock "github.com/stretchr/testify/mock"

	routing "github.com/skycoin/skywire/pkg/routing"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// FindRoutes provides a mock function with given fields: ctx, rts, opts
func (_m *Client) FindRoutes(ctx context.Context, rts []routing.PathEdges, opts *rfclient.RouteOptions) (map[routing.PathEdges][][]routing.Hop, error) {
	ret := _m.Called(ctx, rts, opts)

	var r0 map[routing.PathEdges][][]routing.Hop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []routing.PathEdges, *rfclient.RouteOptions) (map[routing.PathEdges][][]routing.Hop, error)); ok {
		return rf(ctx, rts, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []routing.PathEdges, *rfclient.RouteOptions) map[routing.PathEdges][][]routing.Hop); ok {
		r0 = rf(ctx, rts, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[routing.PathEdges][][]routing.Hop)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []routing.PathEdges, *rfclient.RouteOptions) error); ok {
		r1 = rf(ctx, rts, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
