// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// closeFn is an autogenerated mock type for the closeFn type
type closeFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *closeFn) Execute() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newCloseFn creates a new instance of closeFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newCloseFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *closeFn {
	mock := &closeFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
