// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// dialFunc is an autogenerated mock type for the dialFunc type
type dialFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, addr
func (_m *dialFunc) Execute(ctx context.Context, addr string) (net.Conn, error) {
	ret := _m.Called(ctx, addr)

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (net.Conn, error)); ok {
		return rf(ctx, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) net.Conn); ok {
		r0 = rf(ctx, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newDialFunc creates a new instance of dialFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDialFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *dialFunc {
	mock := &dialFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
