// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// Handshake is an autogenerated mock type for the Handshake type
type Handshake struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Handshake) Execute(_a0 net.Conn) (net.Conn, error) {
	ret := _m.Called(_a0)

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(net.Conn) (net.Conn, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(net.Conn) net.Conn); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(net.Conn) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHandshake creates a new instance of Handshake. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandshake(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handshake {
	mock := &Handshake{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
