// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// sendServicePacketFn is an autogenerated mock type for the sendServicePacketFn type
type sendServicePacketFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: interval
func (_m *sendServicePacketFn) Execute(interval time.Duration) {
	_m.Called(interval)
}

// newSendServicePacketFn creates a new instance of sendServicePacketFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSendServicePacketFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *sendServicePacketFn {
	mock := &sendServicePacketFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
