// gen_proxy_stubs reads pkg/visor/api.go's API interface and emits
// proxy_default_api.go — one method per API entry returning
// ErrProxyNotSupported (or zero values for non-error returns).
//
//	go run /tmp/gen_proxy_stubs.go > pkg/visor/proxy_default_api.go
//	then hand-edit any zero-value return that needs different shape.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "pkg/visor/api.go", nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var iface *ast.InterfaceType
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts := spec.(*ast.TypeSpec)
			if ts.Name.Name == "API" {
				iface = ts.Type.(*ast.InterfaceType)
			}
		}
	}
	if iface == nil {
		fmt.Fprintln(os.Stderr, "API interface not found")
		os.Exit(1)
	}

	fmt.Println(`// Package visor pkg/visor/proxy_default_api.go
//
// Generated by /tmp/gen_proxy_stubs.go from pkg/visor/api.go.
//
// proxyDefaultAPI implements the full API interface by returning
// ErrProxyNotSupported (or the zero value for non-error returns)
// from every method. proxiedVisorAPI embeds it and overrides the
// methods that have HVxxx counterparts on the sub-hypervisor's API.
//
// To regenerate after API changes:
//
//	go run /tmp/gen_proxy_stubs.go > pkg/visor/proxy_default_api.go
package visor

import (
	"encoding/json"
	"net"
	"time"

	"github.com/google/uuid"

	"github.com/skycoin/skywire/pkg/app/appcommon"
	"github.com/skycoin/skywire/pkg/app/appnet"
	"github.com/skycoin/skywire/pkg/app/appserver"
	"github.com/skycoin/skywire/pkg/cipher"
	"github.com/skycoin/skywire/pkg/dmsg/dmsgpty"
	"github.com/skycoin/skywire/pkg/netutil"
	"github.com/skycoin/skywire/pkg/router/setupmetrics"
	"github.com/skycoin/skywire/pkg/routing"
	"github.com/skycoin/skywire/pkg/servicedisc"
	"github.com/skycoin/skywire/pkg/transport"
	"github.com/skycoin/skywire/pkg/visor/dmsgtracker"
	"github.com/skycoin/skywire/pkg/visor/logserver"
	"github.com/skycoin/skywire/pkg/visor/visorconfig"
)

// Suppress unused-import warnings if a particular method set
// doesn't reference all packages — the imports above are scoped to
// the full surface area of api.go.
var _ = json.RawMessage(nil)
var _ net.Conn
var _ time.Duration
var _ uuid.UUID
var _ appcommon.LogStore
var _ = appnet.Addr{}
var _ appserver.AppState
var _ cipher.PubKey
var _ dmsgpty.CommandExecResult
var _ netutil.EphemeralDiagResult
var _ setupmetrics.Metrics
var _ routing.Rule
var _ servicedisc.Service
var _ transport.Entry
var _ dmsgtracker.DmsgClientSummary
var _ logserver.ServiceEntry
var _ visorconfig.Duration

type proxyDefaultAPI struct{}
`)

	for _, m := range iface.Methods.List {
		if len(m.Names) == 0 {
			continue
		}
		name := m.Names[0].Name
		ft := m.Type.(*ast.FuncType)
		emitMethod(name, ft)
	}
}

func emitMethod(name string, ft *ast.FuncType) {
	// Params
	var params []string
	pIdx := 0
	if ft.Params != nil {
		for _, p := range ft.Params.List {
			ts := typeString(p.Type)
			if len(p.Names) == 0 {
				params = append(params, fmt.Sprintf("_ %s", ts))
				pIdx++
				continue
			}
			for range p.Names {
				params = append(params, fmt.Sprintf("_ %s", ts))
				pIdx++
			}
		}
	}
	// Results
	var results []string
	var zeros []string
	if ft.Results != nil {
		for _, r := range ft.Results.List {
			ts := typeString(r.Type)
			n := 1
			if len(r.Names) > 1 {
				n = len(r.Names)
			}
			for i := 0; i < n; i++ {
				results = append(results, ts)
				zeros = append(zeros, zeroValue(ts))
			}
		}
	}
	// Replace last error zero with ErrProxyNotSupported
	if len(results) > 0 && results[len(results)-1] == "error" {
		zeros[len(zeros)-1] = "ErrProxyNotSupported"
	}
	resStr := ""
	if len(results) > 0 {
		if len(results) == 1 {
			resStr = " " + results[0]
		} else {
			resStr = " (" + strings.Join(results, ", ") + ")"
		}
	}
	body := ""
	if len(zeros) > 0 {
		body = "\treturn " + strings.Join(zeros, ", ") + "\n"
	}
	fmt.Printf("func (proxyDefaultAPI) %s(%s)%s {\n%s}\n\n", name, strings.Join(params, ", "), resStr, body)
}

func typeString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeString(t.X)
	case *ast.SelectorExpr:
		return typeString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + typeString(t.Elt)
		}
		return "[...]" + typeString(t.Elt) // not used
	case *ast.MapType:
		return "map[" + typeString(t.Key) + "]" + typeString(t.Value)
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.Ellipsis:
		return "..." + typeString(t.Elt)
	case *ast.ChanType:
		switch t.Dir {
		case ast.SEND:
			return "chan<- " + typeString(t.Value)
		case ast.RECV:
			return "<-chan " + typeString(t.Value)
		default:
			return "chan " + typeString(t.Value)
		}
	case *ast.FuncType:
		return funcTypeString(t)
	}
	return "interface{}"
}

func funcTypeString(t *ast.FuncType) string {
	var sb strings.Builder
	sb.WriteString("func(")
	if t.Params != nil {
		var ps []string
		for _, p := range t.Params.List {
			ts := typeString(p.Type)
			if len(p.Names) == 0 {
				ps = append(ps, ts)
				continue
			}
			for range p.Names {
				ps = append(ps, ts)
			}
		}
		sb.WriteString(strings.Join(ps, ", "))
	}
	sb.WriteString(")")
	if t.Results != nil && len(t.Results.List) > 0 {
		var rs []string
		for _, r := range t.Results.List {
			rs = append(rs, typeString(r.Type))
		}
		sb.WriteString(" ")
		if len(rs) > 1 {
			sb.WriteString("(" + strings.Join(rs, ", ") + ")")
		} else {
			sb.WriteString(rs[0])
		}
	}
	return sb.String()
}

func zeroValue(ts string) string {
	if strings.HasPrefix(ts, "*") || strings.HasPrefix(ts, "[]") || strings.HasPrefix(ts, "map[") || strings.HasPrefix(ts, "chan") || ts == "interface{}" || ts == "error" || strings.HasPrefix(ts, "func(") {
		return "nil"
	}
	switch ts {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64", "uintptr", "byte", "rune":
		return "0"
	}
	// Named integer-alias types — these can't be constructed via {}.
	// Use a numeric zero literal.
	switch ts {
	case "time.Duration", "visorconfig.Duration", "uint16", "routing.RouteID":
		return "0"
	}
	// Interface-typed (net.Conn is an interface) and other interface
	// aliases need nil rather than {}.
	switch ts {
	case "net.Conn", "json.RawMessage", "router.Group", "router.NoiseRouteGroup":
		return "nil"
	}
	// Named struct or composite — use zero value via empty composite literal
	if strings.Contains(ts, ".") || (len(ts) > 0 && ts[0] >= 'A' && ts[0] <= 'Z') {
		return ts + "{}"
	}
	return ts + "{}"
}
