#!/bin/sh
# Wrap TinyGo's wasm_exec.js so its loader class lands on __winboxGo instead of
# globalThis.Go, and write the result to $2.
#
# browse.js's shell path reads an existing globalThis.Go as "the wasm_exec that
# matches the visor blob is already loaded" and skips loading its own. The
# window-manager module is always TinyGo-built while the visor blob may be the
# standard-Go one, so leaking a Go global here would hand the shell the wrong
# loader. Nothing else about the file is changed.
#
# Run by `make embed-winbox`; not meant to be run on its own.
set -eu
src=$1
dst=$2
[ -r "$src" ] || { echo "wrap-winbox-exec: cannot read $src" >&2; exit 1; }
{
	echo "// Code generated by 'make embed-winbox' from TinyGo's targets/wasm_exec.js. DO NOT EDIT."
	echo "//"
	echo "// Wrapped so the loader class lands on __winboxGo instead of globalThis.Go."
	echo "// browse.js's shell path treats an existing globalThis.Go as 'the right"
	echo "// wasm_exec for the visor blob is already loaded' and skips loading its own,"
	echo "// so leaking TinyGo's here would break the shell whenever the visor is the"
	echo "// standard-Go blob. Nothing else about the file is changed."
	echo "globalThis.__winboxGo = (function () {"
	echo "  var had = Object.prototype.hasOwnProperty.call(globalThis, 'Go');"
	echo "  var prev = globalThis.Go;"
	cat "$src"
	echo "  var mine = globalThis.Go;"
	echo "  if (had) { globalThis.Go = prev; } else { try { delete globalThis.Go; } catch (e) { globalThis.Go = undefined; } }"
	echo "  return mine;"
	echo "})();"
} > "$dst"
