// Code generated by mockery v2.52.3. DO NOT EDIT.

package appevent

import (
	context "context"

	appcommon "github.com/skycoin/skywire/pkg/app/appcommon"

	mock "github.com/stretchr/testify/mock"
)

// MockRPCClient is an autogenerated mock type for the RPCClient type
type MockRPCClient struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockRPCClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Hello provides a mock function with no fields
func (_m *MockRPCClient) Hello() *appcommon.Hello {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hello")
	}

	var r0 *appcommon.Hello
	if rf, ok := ret.Get(0).(func() *appcommon.Hello); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appcommon.Hello)
		}
	}

	return r0
}

// Notify provides a mock function with given fields: ctx, e
func (_m *MockRPCClient) Notify(ctx context.Context, e *Event) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Event) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRPCClient creates a new instance of MockRPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRPCClient {
	mock := &MockRPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
