// Code generated by mockery v2.52.3. DO NOT EDIT.

package network

import (
	context "context"

	cipher "github.com/skycoin/skywire/pkg/skywire-utilities/pkg/cipher"

	mock "github.com/stretchr/testify/mock"

	net "net"
)

// MockDialer is an autogenerated mock type for the Dialer type
type MockDialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields: ctx, remote, port
func (_m *MockDialer) Dial(ctx context.Context, remote cipher.PubKey, port uint16) (net.Conn, error) {
	ret := _m.Called(ctx, remote, port)

	if len(ret) == 0 {
		panic("no return value specified for Dial")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, cipher.PubKey, uint16) (net.Conn, error)); ok {
		return rf(ctx, remote, port)
	}
	if rf, ok := ret.Get(0).(func(context.Context, cipher.PubKey, uint16) net.Conn); ok {
		r0 = rf(ctx, remote, port)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, cipher.PubKey, uint16) error); ok {
		r1 = rf(ctx, remote, port)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Type provides a mock function with no fields
func (_m *MockDialer) Type() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewMockDialer creates a new instance of MockDialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialer {
	mock := &MockDialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
