name: Release
# only trigger on pull request closed events
on:
  push:
    tags:
      - '*'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          sudo apt update
          sudo snap install goreleaser --classic
          make dep-github-release
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make github-release

  darwin:
    needs: linux
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: actions/checkout@v4
      - name: Install Requirements
        run: |
          brew install goreleaser
          brew install jq
          brew install wget
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release-darwin
          make mac-installer-release

  windows:
    needs: darwin
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - uses: actions/checkout@v4
      - name: Install Requirements
        shell: pwsh
        run: |
          Invoke-WebRequest "https://github.com/goreleaser/goreleaser/releases/download/v2.0.1/goreleaser_Windows_x86_64.zip" -OutFile goreleaser.zip
          Expand-Archive goreleaser.zip
          choco install make
      - name: Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release-windows
          make windows-installer-release
  publish-winget:
    needs: windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install wingetcreate
        run: |
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.zip
          Expand-Archive wingetcreate.zip -DestinationPath .
          echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Publish to winget
        run: |
          wingetcreate update Skycoin.Skywire `
            --urls "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/skywire-installer-${{ github.ref_name }}-windows-amd64.msi" `
                   "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/skywire-installer-${{ github.ref_name }}-windows-386.msi" `
            --submit --token $env:WINGETCREATE_TOKEN
        env:
          WINGETCREATE_TOKEN: ${{ secrets.WINGET_PAT }}
